-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
12
best.h is :
12
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
12
best.h is :
12
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
    01234567890123456
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
14
best.h is :
11
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
    01234567890123456
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
12
best.h is :
12
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
    01234567890123456
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
12
best.h is :
12
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
012345678901234567890123456789
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
13
best.h is :
3
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
before skip line
start of skip_line
012345678901234567890123456789
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
14
best.h is :
3
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
before skip line
start of skip_line

-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
012345678901234567890123456789
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
13
best.h is :
3
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
before skip line
start of skip_line
012345678901234567890123456789
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
14
best.h is :
3
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
before skip line
start of skip_line

-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
012345678901234567890123456789
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
13
best.h is :
3
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
before skip line
start of skip_line
012345678901234567890123456789
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
14
best.h is :
3
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
before skip line
start of skip_line

get map size end
fill map start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
    01234567890123456
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
13
best.h is :
11
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
    01234567890123456
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
14
best.h is :
11
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
-----NEW RUN------

start of main

player determine start
player determine end
before play.

start of play.

get map start
get map size start
before skip line
start of skip_line
    01234567890123456
get map size end
fill map start
fill map end
get map end
after getmap.

after create heat

after get piece

after get heat

start of try_piece

start of score_piece

end of score_piece

start of score_piece

end of score_piece

best.w is :
14
best.h is :
11
end of try_piece

after try piece

end of play.
start of play.

get map start
get map size start
